spring:
  application:
    name: dental-clinic-service
  profiles:
    default: local
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.server.csrf: TRACE